### ISSUE TITLE
App does not work as expected, crashes after trying to save photo (API level 24)

### ISSUE THREAD

**Issue by jose-ramirez** [udacity/AdvancedAndroid_Emojify#2]
After taking a photo from the app, the photo doesn't show up at the main screen; i.e., only the floating buttons appear after the camera app returns with a result. Then, after clicking the save button, the app crashes.

So, I decided to run the app in debug mode, and I saw that the problem was that after the result from the camera app comes back to MainActivity, the variable `mTempPhotoPath` no longer has the value that was assigned to it initially when the method `launchCamera()` was called, so, even if the result was positive, the function `resamplePic()` can't do anything because the image path it receives is now `null`.

As a possible fix, I just saved the value of `mTempPhotoPath` to the activity's `Bundle`, and retrieve it inside `onCreate()` if necessary. After that the app now works as expected.

**Comment by ikakus** [comment]
On samsung galaxy tab 3.(API 17) ,even with @hpRamirez suggested bug-fix which occurs because of samsung camera app changes the orientation , `resamplePic()` retruns null because it cannot decode Bmp from given path.

**Comment by mohammedgmgn** [comment]
@hpRamirez 
could you please share your modification code

**Comment by ngamolsky** [comment]
Hi all, 

Thanks for bringing that to my attention! Turns out that if your Activity is completely destroyed due to memory consumption, you will indeed lose the mTempPhotoPath variable. You should already know how to persist it, either using the SaveInstanceState (as described [here](https://developer.android.com/guide/components/activities/activity-lifecycle.html#saras)) or any other persistence method.

**Comment by ikakus** [comment]
@ngamolsky It does not work properly on samsung devices, and reason is not activity being destroyed.

**Comment by ngamolsky** [comment]
@ikakus  Can you share your stacktrace? It works on my Samsung S7.

- N

**Comment by acrozes** [comment]
The stacktrace on Samsung S4:

```

05-30 04:41:48.034 12536-12536/com.example.android.emojify E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.example.android.emojify, PID: 12536
                                                                             java.lang.RuntimeException: Unable to resume activity {com.example.android.emojify/com.example.android.emojify.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {com.example.android.emojify/com.example.android.emojify.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                                 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3403)
                                                                                 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3434)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772)
                                                                                 at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4471)
                                                                                 at android.app.ActivityThread.access$1000(ActivityThread.java:177)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1455)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:145)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
                                                                              Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {com.example.android.emojify/com.example.android.emojify.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                                 at android.app.ActivityThread.deliverResults(ActivityThread.java:4067)
                                                                                 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3389)
                                                                                 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3434) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772) 
                                                                                 at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4471) 
                                                                                 at android.app.ActivityThread.access$1000(ActivityThread.java:177) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1455) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:145) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5951) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 
                                                                              Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                                 at com.google.android.gms.vision.Frame$Builder.setBitmap(Unknown Source)
                                                                                 at com.example.android.emojify.Emojifier.detectFaces(Emojifier.java:32)
                                                                                 at com.example.android.emojify.MainActivity.processAndSetImage(MainActivity.java:188)
                                                                                 at com.example.android.emojify.MainActivity.onActivityResult(MainActivity.java:164)
                                                                                 at android.app.Activity.dispatchActivityResult(Activity.java:6549)
                                                                                 at android.app.ActivityThread.deliverResults(ActivityThread.java:4063)
                                                                                 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3389) 
                                                                                 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3434) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772) 
                                                                                 at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4471) 
                                                                                 at android.app.ActivityThread.access$1000(ActivityThread.java:177) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1455) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:145) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5951) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 

```

**Comment by vishalenrique** [comment]
@acrozes I had the same error 
https://stackoverflow.com/questions/24467696/android-file-provider-permission-denial
this worked for me
