### ISSUE TITLE
App force closes after clicking "GO" button 

### ISSUE THREAD

**Issue by sagar-pardhi** [udacity/AdvancedAndroid_Emojify#3]
### Here is the stack trace

05-08 21:23:03.619 6885-6885/com.example.android.emojify E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.example.android.emojify, PID: 6885
                                                                           java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                               at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:289)
                                                                               at android.view.View.performClick(View.java:4652)
                                                                               at android.view.View$PerformClick.run(View.java:19318)
                                                                               at android.os.Handler.handleCallback(Handler.java:733)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:146)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5641)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1288)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1104)
                                                                               at dalvik.system.NativeStart.main(Native Method)
                                                                            Caused by: java.lang.reflect.InvocationTargetException
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                               at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:284)
                                                                               at android.view.View.performClick(View.java:4652) 
                                                                               at android.view.View$PerformClick.run(View.java:19318) 
                                                                               at android.os.Handler.handleCallback(Handler.java:733) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                               at android.os.Looper.loop(Looper.java:146) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5641) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1288) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1104) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                                            Caused by: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/com.example.android.emojify/cache/JPEG_2017508_212303_-791874679.jpg
                                                                               at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:678)
                                                                               at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:377)
                                                                               at com.example.android.emojify.MainActivity.launchCamera(MainActivity.java:108)
                                                                               at com.example.android.emojify.MainActivity.emojifyMe(MainActivity.java:69)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                               at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:284) 
                                                                               at android.view.View.performClick(View.java:4652) 
                                                                               at android.view.View$PerformClick.run(View.java:19318) 
                                                                               at android.os.Handler.handleCallback(Handler.java:733) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                               at android.os.Looper.loop(Looper.java:146) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5641) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1288) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1104) 
                                                                               at dalvik.system.NativeStart.main(Native Method)

**Comment by sagar-pardhi** [comment]
@ngamolsky Please review this error, i am not getting it

**Comment by ngamolsky** [comment]
Hi There! Thanks for submitting the ticket. Are you running the code from this branch directly or is your code slightly different? Also, what device are you testing it on? @sagar-pardhi

**Comment by sagar-pardhi** [comment]
Yes i have created a new project in android studio and copied the starter code over there you can take a look to my project over here https://github.com/sagar-pardhi/Emojify @ngamolsky
